Check status of deploy

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -52,3 +52,18 @@ jobs:
         app-name: ${{ secrets.FUNCTION_APP }}
         package: ${{ github.workspace }}
         publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
+
+    - name: 'Check deploy succeeded'
+      run: |
+        i=0
+        while [ $i -le 10 ]; do
+          sleep 10
+          RESPONSE=$(curl -sv "${steps.fa.outputs.app-url}/_ping 2>&1 | grep Starling-Sweeper-Version | cut -d" " -f3")
+          if [ "${RESPONSE}" = "${GITHUB_SHA}" ]; then
+            exit 0
+          fi
+          i=$((i+1))
+        done
+        echo "Failed to deploy."
+        echo -e "Exp: ${GITHUB_SHA}\nGot: ${RESPONSE}."
+        exit 1
